# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: HOONSEOK YOON
# title: Senior Network System Administrator
email: HOONSEOK123@YONSEI.AC.KR
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  seokyhoon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: seokyhoon
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0007-1481-7723

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Image.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hoonseok Yoon and I'm a student from South Korea.

  A highly motivated and detail-oriented student specializing in Digital Healthcare at the College of Software and Digital Healthcare, with a strong foundation in software development, big data analysis, and AI applications. Possesses hands-on experience in developing software solutions and analyzing complex datasets to drive innovation in healthcare technologies. 

  I have actively participated in AI-driven medical research projects, focusing on deep learning applications in medical imaging, predictive modeling, and healthcare data analytics. My experience includes developing ML models for age prediction, disease detection, and medical image segmentation using state-of-the-art machine learning techniques, including CNNs, LSTMs, and generative AI. 

  Beyond academics and research, I am deeply passionate about exploring innovative ways to bridge the gap between AI and practical healthcare applications. I enjoy tackling challenging problems, experimenting with new AI models, and leveraging data-driven insights to improve healthcare solutions. 

  Outside of work and studies, I have a strong passion for sports, including soccer and golf. I also love driving and listening to music, which helps me relax and stay inspired. These hobbies allow me to maintain a balanced and creative mindset while continuously pushing myself to achieve new goals.

  

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: text
        title: Yonsei University, Wonju, South Korea
        caption: 03/2021 - 02/2025
        sub_title: Bachelor of Science (B.S.) in Digital Healthcare and Advanced Digital Healthcare
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
            **Honors and Awards**
            - Scholarship for academic excellence (2024)
            - Merit-based scholarship for SW majors (2023, 2024)
            - Data Impact Global Startup Camp, IR Competition, Grand Award (2023)
            - Busan National Smart IoT Competition, Encouragement Award (2022)
            - Lifelog Big Data Utilization and Proposal Hackathon, Encouragement Award (2022)
      
            **Research Interests**
            - Deep learning applications in medical imaging and digital healthcare
            - Data science with machine learning
            - Generative AI and medical image processing
      
            **Selected Coursework**
            - Introduction of Database System, Artificial Intelligence, Medical Artificial Intelligence, Image Processing, Digital Signal Processing, Python Programming, Java Programming, Open Software and Linux, Operating System, SW Engineer Seminar
      
            **Activities**
            - Campus Tutor for Introductory Liberal Arts Courses (Computational Thinking (Python)), Spring Semester 2023, Software Tutoring Program
            - 25th Summer University Student Talent Volunteer Camp, 2022, University Volunteer Camp
 
  - title: Publications
    layout: text
    content: |
      ## 1. **Assessing Machine Learning Models for Predicting Age with Intracranial Vessel Tortuosity and Thickness Information**  
      **📖 Published in**: *Brain Sciences 13.11 (2023): 1512*  

      **Authors**: **Yoon, Hoon-Seok**, Jeongmin Oh, and Yoon-Chul Kim  

      <!-- new line -->

      ## 2. **Machine Learning-Based Age Prediction with Feature Subset Selection from MR Angiography Data**  
      **📌 Status**: In revision  

      **Authors**: **Yoon, Hoon-Seok**, Yoon-Chul Kim  

      

  - title: Work Experience
    layout: list
    content:
      - layout: text
        title: Medical Artificial Intelligence (MAI) Lab, Yonsei University
        caption: 12/2022 - Present
        sub_title: Undergraduate Researcher
        description: |
            - Developed and implemented ML models to analyze medical data (including over 160 CT image series, 600 MR brain images, and ECG and EEG data) for age prediction, heart disease detection, and anomaly detection.
            - Applied deep learning techniques, including CNN and generative AI, to enhance image segmentation and disease detection accuracy.
  
  - title: Project Experience
    layout: text
    content: |
      ## 1. **Development of Automatic Spine Level Segmentation Software Using AI**  
      **📅 03/2024 - 11/2024 | 🎭 Team Member & Presenter**  
      - Collaborated on an industry-academic project to develop a deep learning algorithm for automatic spine level identification using CT images, improving the F1 score by 0.15.  
      - Verified results with pre-trained models (DenseNet121, EfficientNetB0, ResNet34) and enhanced accuracy using data augmentation techniques like diffusion models and GANs.  

    

      ## 2. **Non-Seen Handwritten Letter Image Sorting**  
      **📅 03/2024 - 06/2024 | 🎭 Developer**  
      - Created an AI system to classify handwritten letter sequences using CNN and RNN, refining network structures through extensive experiments.  
      - Implemented LSTM networks for sequential data, improving validation accuracy, and optimized parameters like batch size, hidden size, and dropout rate via hyperparameter tuning.  

   

      ## 3. **ML-Based Age Prediction from MR Angiography Data**  
      **📅 11/2023 - 05/2024 | 🎭 Developer for MAI Lab**  
      - Evaluated ML model performance using feature selection methods (CFS, Relief-F) to create feature subsets, with CFS yielding superior results.  
      - Analyzed key features influencing the model and utilized SHAP plots to visualize feature relationships.  

 

      ## 4. **Deep Learning Project in ECG Classification**  
      **📅 10/2023 - 12/2023 | 🎭 Team Leader & Presenter**  
      - Integrated BLSTM networks to capture temporal patterns in ECG data, achieving a slight accuracy improvement over the baseline model.  
      - Evaluated pre-trained models to optimize arrhythmia detection, selecting the best model based on F1 score.  

      ---

      ## 5. **Medical Big Data Analytics Project**  
      **📅 09/2023 - 04/2024 | 🎭 Team Leader & Presenter**  
      - Analyzed aging patterns using NHIS data, focusing on blood glucose and cholesterol level changes across age groups.  
      - Developed a regression model for age prediction, using SHAP to interpret key health features associated with aging.  

      ---

      ## 6. **Assessing Machine Learning Models for Predicting Age**  
      **📅 01/2023 - 10/2023 | 🎭 Team Member**  
      - Developed six ML models, including Random Forest, Linear Regression, and XGBoost, to predict age using MRA data features (e.g., vessel tortuosity and diameter).  
      - Led feature engineering, cross-validation, and hyperparameter tuning, improving RMSE and R² model performance.  

      ---

      ## 7. **Research on EEG-Based Technology to Improve Drivers' Cognitive Abilities**  
      **📅 03/2023 - 06/2023 | 🎭 Developer**  
      - Analyzed EEG data to detect patterns of cognitive impairment in drivers, identifying signs of impaired driving.  
      - Designed an application using JavaScript and developed a database system to store biometric and driving data.  

  
  - title: Personal
    layout: text
    content: |
      - **Programming Languages(e.g., Python, C language, Java)**
      
      - **Machine Learning, Deep Learning Technologies**
      
      - **Big Data Analysis Tools**
      
      - **Communication Skills**
      
      - **Team Collaboration**

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
