# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: HOONSEOK YOON
# title: Senior Network System Administrator
email: HOONSEOK123@YONSEI.AC.KR
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  seokyhoon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: seokyhoon
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0007-1481-7723

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hoonseok Yoon and I'm a student from South Korea.
  

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: text
        title: Yonsei University, Wonju, South Korea
        caption: 03/2021 - 02/2025
        sub_title: Bachelor of Science (B.S.) in Digital Healthcare and Advanced Digital Healthcare
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
            **Honors**
            - Scholarship for academic excellence (2024)
            - Merit-based scholarship for SW majors (2023, 2024)
            - Data Impact Global Startup Camp, IR Competition, Grand Award (2023)
            - Busan National Smart IoT Competition, Encouragement Award (2022)
            - Lifelog Big Data Utilization and Proposal Hackathon, Encouragement Award (2022)
      
            **Research Interests**
            - Deep learning applications in medical imaging and digital healthcare
            - Data science with machine learning
            - Generative AI and medical image processing
      
            **Selected Coursework**
            - Introduction of Database System, Artificial Intelligence, Medical Artificial Intelligence, Image Processing, Digital Signal Processing, Python Programming, Java Programming, Open Software and Linux, Operating System, SW Engineer Seminar
      
            **Activities**
            - Campus Tutor for Introductory Liberal Arts Courses (Computational Thinking (Python)), Spring Semester 2023, Software Tutoring Program
            - 25th Summer University Student Talent Volunteer Camp, 2022, University Volunteer Camp
 - title: Publications
  layout: list
  content:
    - layout: text
      title: "Assessing machine learning models for predicting age with intracranial vessel tortuosity and thickness information"
      caption: Brain Sciences 13.11 (2023): 1512
      sub_title: Yoon, Hoon-Seok, Jeongmin Oh, and Yoon-Chul Kim

    - layout: text
      title: "Machine learning-based age prediction with feature subset selection from MR angiography data"
      caption: In revision
      sub_title: Yoon, Hoon-Seok, Yoon-Chul Kim

- title: Work Experience
  layout: list
  content:
    - layout: text
      title: Medical Artificial Intelligence (MAI) Lab, Wonju, South Korea
      caption: 12/2022 - Present
      sub_title: Undergraduate Researcher
      description: |
          - Developed and implemented ML models to analyze medical data (including over 160 CT image series, 600 MR brain images, and ECG and EEG data) for age prediction, heart disease detection, and anomaly detection.
          - Applied deep learning techniques, including CNN and generative AI, to enhance image segmentation and disease detection accuracy.

- title: Project Experience
  layout: list
  content:
    - layout: text
      title: Development of Automatic Spine Level Segmentation Software Using AI
      caption: 03/2024 - 11/2024
      sub_title: Team Member & Presenter
      description: |
          - Collaborated on an industry-academic project to develop a deep learning algorithm for automatic spine level identification using CT images, improving the F1 score by 0.15.
          - Verified results with pre-trained models (DenseNet121, EfficientNetB0, ResNet34) and enhanced accuracy using data augmentation techniques like diffusion models and GANs.

    - layout: text
      title: Non-Seen Handwritten Letter Image Sorting
      caption: 03/2024 - 06/2024
      sub_title: Developer
      description: |
          - Created an AI system to classify handwritten letter sequences using CNN and RNN, refining network structures through extensive experiments.
          - Implemented LSTM networks for sequential data, improving validation accuracy, and optimized parameters like batch size, hidden size, and dropout rate via hyperparameter tuning.

    - layout: text
      title: ML Based Age Prediction from MR Angiography Data
      caption: 11/2023 - 05/2024
      sub_title: Developer for MAI Lab
      description: |
          - Evaluated ML model performance using feature selection methods (CFS, Relief-F) to create feature subsets, with CFS yielding superior results.
          - Analyzed key features influencing the model and utilized SHAP plots to visualize feature relationships.

    - layout: text
      title: Deep Learning Project in ECG Classification
      caption: 10/2023 - 12/2023
      sub_title: Team Leader & Presenter
      description: |
          - Integrated BLSTM networks to capture temporal patterns in ECG data, achieving a slight accuracy improvement over the baseline model.
          - Evaluated pre-trained models to optimize arrhythmia detection, selecting the best model based on F1 score.

    - layout: text
      title: Medical Big Data Analytics Project
      caption: 09/2023 - 04/2024
      sub_title: Team Leader & Presenter
      description: |
          - Analyzed aging patterns using NHIS data, focusing on blood glucose and cholesterol level changes across age groups.
          - Developed a regression model for age prediction, using SHAP to interpret key health features associated with aging.

    - layout: text
      title: Assessing Machine Learning Models for Predicting Age
      caption: 01/2023 - 10/2023
      sub_title: Team Member
      description: |
          - Developed six ML models, including Random Forest, Linear Regression, and XGBoost, to predict age using MRA data features (e.g., vessel tortuosity and diameter).
          - Led feature engineering, cross-validation, and hyperparameter tuning, improving RMSE and R² model performance.

    - layout: text
      title: Research on EEG-Based Technology to Improve Drivers' Cognitive Abilities
      caption: 03/2023 - 06/2023
      sub_title: Developer
      description: |
          - Analyzed EEG data to detect patterns of cognitive impairment in drivers, identifying signs of impaired driving.
          - Designed an application using JavaScript and developed a database system to store biometric and driving data.

- title: Personal
  layout: list
  content:
    - layout: text
      title: Programming Languages
      description: Python, C, Java

    - layout: text
      title: Machine Learning & Deep Learning Technologies
      description: Experience with ML models, deep learning frameworks, CNNs, RNNs, and generative AI.

    - layout: text
      title: Big Data Analysis Tools
      description: Experience with data processing, feature engineering, and ML model evaluation.

    - layout: text
      title: Communication Skills
      description: Strong presentation and teamwork abilities, demonstrated through research and project collaborations.

    - layout: text
      title: Team Collaboration
      description: Experience leading and participating in multi-disciplinary AI projects.         
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
